NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.oneOrg.51mm.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.oneOrg.51mm.com-cert.pem
    OrganizationalUnitIdentifier: peer
