version: '2'

networks:
  default:

services:

  couch.peer0.oneOrg.51mm.com:
    container_name: couch.peer0.oneOrg.51mm.com
    image: hyperledger/fabric-couchdb
    privileged: true
    environment:
      - GODEBUG=netdns=go
      - COUCHDB_USER=couchadmin
      - COUCHDB_PASSWORD=adminpwd
    ports:
      - 8984:5984
    networks:
      - default  
