version: '2'

networks:
  default:

services:

  order1.51mm.com:
    container_name: order1.51mm.com
    image: hyperledger/fabric-orderer
    privileged: true
    environment:
      - GODEBUG=netdns=go
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=order
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=3s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=50s
      - ORDERER_KAFKA_VERBOSE=true

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 8050:7050

    extra_hosts:
      - "order2.51mm.com:192.168.1.110"
      - "order3.51mm.com:192.168.1.110"

    volumes:
      - /var/certification/8ef272034af598974db7a65b2c01b696/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /var/certification/8ef272034af598974db7a65b2c01b696/crypto-config/ordererOrganizations/51mm.com/orderers/order1.51mm.com/msp:/var/hyperledger/orderer/msp
      - /var/certification/8ef272034af598974db7a65b2c01b696/crypto-config/ordererOrganizations/51mm.com/orderers/order1.51mm.com/tls:/var/hyperledger/orderer/tls
    networks:
      - default
