version: '2'

networks:
  default:

services:
  peer1.oneOrg.51mm.com:
    container_name: peer1.oneOrg.51mm.com
    privileged: true
    image: hyperledger/fabric-peer
    dns_search: .
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=8ef272034af598974db7a65b2c01b696_default
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.oneOrg.51mm.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_ID=peer1.oneOrg.51mm.com
      - CORE_PEER_LOCALMSPID=oneOrg
      - CORE_PEER_ADDRESS=peer1.oneOrg.51mm.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.oneOrg.51mm.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.oneOrg.51mm.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
#########COUCH_Start
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couch.peer1.oneOrg.51mm.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchadmin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpwd
#########COUCH_End
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - /var/certification/8ef272034af598974db7a65b2c01b696/crypto-config/peerOrganizations/oneOrg.51mm.com/peers/peer1.oneOrg.51mm.com/msp:/etc/hyperledger/fabric/msp
      - /var/certification/8ef272034af598974db7a65b2c01b696/crypto-config/peerOrganizations/oneOrg.51mm.com/peers/peer1.oneOrg.51mm.com/tls:/etc/hyperledger/fabric/tls

    extra_hosts:
      - order0.51mm.com:192.168.1.31
      - order1.51mm.com:192.168.1.31

    depends_on:
      - order2.51mm.com
      - order3.51mm.com
      - couch.peer1.oneOrg.51mm.com
    networks:
      - default
      