

Organizations:

    - &OrdererOrg
        Name: order
        ID: order
        MSPDir: /home/czp/PycharmProjects/baas/certification/cc049e6edbde8144259b50ec9e008120/crypto-config/ordererOrganizations/51mm.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('order.member')"
            Writers:
                Type: Signature
                Rule: "OR('order.member')"
            Admins:
                Type: Signature
                Rule: "OR('order.admin')"
#######List-Start
    - &mmOrg
        Name: mmOrg
        ID: mmOrg
        MSPDir: /home/czp/PycharmProjects/baas/certification/cc049e6edbde8144259b50ec9e008120/crypto-config/peerOrganizations/mmOrg.51mm.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('mmOrg.admin', 'mmOrg.peer', 'mmOrg.client')"
            Writers:
                Type: Signature
                Rule: "OR('mmOrg.admin', 'mmOrg.client')"
            Admins:
                Type: Signature
                Rule: "OR('mmOrg.admin')"
        AnchorPeers:
            - Host: 192.168.0.203
              Port: 7051
#######List-End
#######List-Start
    - &oneOrg
        Name: oneOrg
        ID: oneOrg
        MSPDir: /home/czp/PycharmProjects/baas/certification/cc049e6edbde8144259b50ec9e008120/crypto-config/peerOrganizations/oneOrg.51mm.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('oneOrg.admin', 'oneOrg.peer', 'oneOrg.client')"
            Writers:
                Type: Signature
                Rule: "OR('oneOrg.admin', 'oneOrg.client')"
            Admins:
                Type: Signature
                Rule: "OR('oneOrg.admin')"
        AnchorPeers:
            - Host: 192.168.0.203
              Port: 9051
#######List-End

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

    OrdererType: solo

    Addresses:
#######OrderList-Start
      - order0.51mm.com:7050
#######OrderList-End
#######OrderList-Start
      - order1.51mm.com:8050
#######OrderList-End

    BatchTimeout: 4s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    ProjectOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
#######List-Start
                    - *mmOrg
#######List-End
#######List-Start
                    - *oneOrg
#######List-End

    ProjectOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
#######List-Start
              - *mmOrg
#######List-End
#######List-Start
              - *oneOrg
#######List-End
            Capabilities:
                <<: *ApplicationCapabilities

    SampleMultiNodeEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
#######OrderList-Start
                    - Host: order0.51mm.com
                      Port: 7050
                      ClientTLSCert: /home/czp/PycharmProjects/baas/certification/cc049e6edbde8144259b50ec9e008120/crypto-config/ordererOrganizations/51mm.com/orderers/order0.51mm.com/tls/server.crt
                      ServerTLSCert: /home/czp/PycharmProjects/baas/certification/cc049e6edbde8144259b50ec9e008120/crypto-config/ordererOrganizations/51mm.com/orderers/order0.51mm.com/tls/server.crt
#######OrderList-End
#######OrderList-Start
                    - Host: order1.51mm.com
                      Port: 7050
                      ClientTLSCert: /home/czp/PycharmProjects/baas/certification/cc049e6edbde8144259b50ec9e008120/crypto-config/ordererOrganizations/51mm.com/orderers/order1.51mm.com/tls/server.crt
                      ServerTLSCert: /home/czp/PycharmProjects/baas/certification/cc049e6edbde8144259b50ec9e008120/crypto-config/ordererOrganizations/51mm.com/orderers/order1.51mm.com/tls/server.crt
#######OrderList-End

            Addresses:
#######OrderList-Start
                - order0.51mm.com:7050
#######OrderList-End
#######OrderList-Start
                - order1.51mm.com:7050
#######OrderList-End

            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - <<: *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
#######List-Start
                  - *mmOrg
#######List-End
#######List-Start
                  - *oneOrg
#######List-End

