
Organizations:
    - &-OrgIDForReplace-
        Name: -OrgIDForReplace-
        ID: -OrgIDForReplace-
        MSPDir: -ProjectDIR-/crypto-config/peerOrganizations/-OrgIDForReplace-.-DomainForReplace-/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('-OrgIDForReplace-.admin', '-OrgIDForReplace-.peer', '-OrgIDForReplace-.client')"
            Writers:
                Type: Signature
                Rule: "OR('-OrgIDForReplace-.admin', '-OrgIDForReplace-.client')"
            Admins:
                Type: Signature
                Rule: "OR('-OrgIDForReplace-.admin')"
        AnchorPeers:
            - Host: -AnchorIPForReplace-
              Port: -AnchorPortForReplace-
